COUNTRY_LIST: list[str] = ['France', 'United States', 'Mexico', 'India', 'Spain', 'China',
                           'Canada', 'Germany', 'Switzerland', 'Belgium', 'Hong Kong',
                           'Austria', 'Japan', 'United Kingdom', 'Australia', 'Indonesia',
                           'United Arab Emirates', 'Russia', 'Chile', 'Monaco',
                           'Czech Republic', 'Sweden', 'Thailand', 'Uzbekistan',
                           'Singapore', 'Nigeria', 'Israel', 'Italy', 'South Africa',
                           'Brazil', 'Malaysia', 'South Korea', 'New Zealand', 'Philippines',
                           'Taiwan', 'Norway', 'Egypt', 'Denmark', 'Eswatini (Swaziland)',
                           'Colombia', 'Netherlands', 'Poland', 'Bahamas', 'Ukraine',
                           'Cayman Islands', 'Greece', 'Turkey', 'Argentina', 'Georgia',
                           'Portugal', 'Kazakhstan', 'Algeria', 'Vietnam', 'Latvia',
                           'Finland', 'Bermuda', 'Luxembourg', 'British Virgin Islands',
                           'Cambodia', 'Lebanon', 'Oman', 'Ireland', 'Cyprus', 'Guernsey',
                           'Liechtenstein', 'Turks and Caicos Islands', 'Romania', 'Qatar',
                           'Uruguay', 'Nepal', 'Slovakia', 'Morocco', 'Hungary', 'Tanzania',
                           'Bahrain', 'Peru', 'Andorra', 'Armenia', 'Saudi Arabia']

COUNTRY_LIST_ALL: list[str] = ['France', 'United States', 'Mexico', 'India', 'Spain', 'China',
                               'Canada', 'Germany', 'Switzerland', 'Belgium', 'Hong Kong',
                               'Austria', 'Japan', 'United Kingdom', 'Australia', 'Indonesia',
                               'United Arab Emirates', 'Russia', 'Chile', 'Monaco',
                               'Czech Republic', 'Sweden', 'Thailand', 'Uzbekistan',
                               'Singapore', 'Nigeria', 'Israel', 'Italy', 'South Africa',
                               'Brazil', 'Malaysia', 'South Korea', 'New Zealand', 'Philippines',
                               'Taiwan', 'Norway', 'Egypt', 'Denmark', 'Eswatini (Swaziland)',
                               'Colombia', 'Netherlands', 'Poland', 'Bahamas', 'Ukraine',
                               'Cayman Islands', 'Greece', 'Turkey', 'Argentina', 'Georgia',
                               'Portugal', 'Kazakhstan', 'Algeria', 'Vietnam', 'Latvia',
                               'Finland', 'Bermuda', 'Luxembourg', 'British Virgin Islands',
                               'Cambodia', 'Lebanon', 'Oman', 'Ireland', 'Cyprus', 'Guernsey',
                               'Liechtenstein', 'Turks and Caicos Islands', 'Romania', 'Qatar',
                               'Uruguay', 'Nepal', 'Slovakia', 'Morocco', 'Hungary', 'Tanzania',
                               'Bahrain', 'Peru', 'Andorra', 'Armenia', 'Saudi Arabia', 'All']

INDUSTRY_LIST: list[str] = [
    'Fashion & Retail',
    'Automotive',
    'Technology',
    'Finance & Investments',
    'Media & Entertainment',
    'Telecom',
    'Diversified',
    'Food & Beverage',
    'Logistics',
    'Gambling & Casinos',
    'Manufacturing',
    'Real Estate',
    'Metals & Mining',
    'Energy',
    'Healthcare',
    'Service',
    'Construction & Engineering',
    'Sports',
]

INDUSTRY_LIST_ALL: list[str] = [
    'Fashion & Retail',
    'Automotive',
    'Technology',
    'Finance & Investments',
    'Media & Entertainment',
    'Telecom',
    'Diversified',
    'Food & Beverage',
    'Logistics',
    'Gambling & Casinos',
    'Manufacturing',
    'Real Estate',
    'Metals & Mining',
    'Energy',
    'Healthcare',
    'Service',
    'Construction & Engineering',
    'Sports',
    'All',
]

MONTH_NAMES: dict[int, str] = {
    1: 'Jan',
    2: 'Feb',
    3: 'Mar',
    4: 'Apr',
    5: 'May',
    6: 'Jun',
    7: 'Jul',
    8: 'Aug',
    9: 'Sep',
    10: 'Oct',
    11: 'Nov',
    12: 'Dec'
}

NUMERIC_COLUMNS: list[str] = ['cpi_country', 'cpi_change_country', 'gdp_country',
                              'gross_tertiary_education_enrollment',
                              'gross_primary_education_enrollment_country', 'life_expectancy_country',
                              'tax_revenue_country_country', 'total_tax_rate_country',
                              'population_country', 'nBillionairesCtr', 'totalWealthCtr', 'meanWealthCtr']


US_STATES_ALL: list[str] = ['All', 'Unknown', 'Texas', 'Washington', 'Hawaii', 'Nebraska', 'New York',
                            'California', 'Kansas', 'Arkansas', 'Oregon', 'Virginia',
                            'Wyoming', 'Nevada', 'Florida', 'Pennsylvania', 'Massachusetts',
                            'Illinois', 'Tennessee', 'Connecticut', 'Oklahoma', 'Michigan',
                            'Wisconsin', 'Colorado', 'Indiana', 'New Hampshire', 'Georgia',
                            'Missouri', 'New Jersey', 'North Carolina', 'Iowa', 'Kentucky',
                            'Maryland', 'Montana', 'Ohio', 'South Carolina', 'Arizona',
                            'Louisiana', 'Utah', 'Rhode Island', 'Idaho',
                            'U.S. Virgin Islands', 'Minnesota', 'Maine', 'Mississippi',
                            'South Dakota', 'Alabama']
